---
micronaut:
  application:
    name: booklist2

---
postgres:
  reactive:
    client:
      port: 5432
      host: localhost
      database: booklist
#      user: user
#      password: password
#      maxSize: 5
